### ISSUE TITLE
Drop commas after i.e. and e.g.

### ISSUE THREAD

**Issue by fm2003** [sttp-book/sttp-book#77]
Right now, there are commas after i.e. and e.g. throughout the book. But since we switched to British English (#36), it's best to switch to the "British" style of having no commas after i.e. and e.g. Let's do this in one go, with a search-replace action.

**Comment by HellboundHound** [comment]
Fixed in this pull request: https://github.com/sttp-book/sttp-book/pull/99

Kind regards,
Danny Breunissen

**Comment by mauricioaniche** [comment]
Still thinking about this one, folks. See https://www.dailywritingtips.com/comma-after-i-e-and-e-g/.

**Comment by fm2003** [comment]
> 
> 
> Still thinking about this one, folks. See https://www.dailywritingtips.com/comma-after-i-e-and-e-g/.

That website does say "The consensus seems to be in favor of the comma in American usage; against it in British usage."  It then proceeds to give examples of British style guides that do not use a comma after i.e. and e.g. (The other examples are from American style guides.)

Of course this is not a black and white thing. We can always decide to use British spelling but American style commas. But it seems more consistent to follow the "consensus".

**Comment by mauricioaniche** [comment]
"consensus" is the key here. Not sure what other communities do, but software engineering research papers use comma 100% of times. Maybe that's why my eyes burn whenever I don't see a comma.

Personally, I think it also makes sense, as i.e. is basically "in other words,". Maybe in a few cases we use e.g. it could be replaced by "e.g. A, B, and C", without the comma. Actually, I think it should represent what type of pause you want the reader to have there... which I believe we usually want between "in other words", or "for example".

I'm quite inclined in having the comma. I'll take a decision soon. Thank you all for giving me your opinion!
